name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Uploads repository content to the runner
        with:
          repository: "panos5/release_notes_automation" # The one of the available inputs, visit https://github.com/actions/checkout#readme to find more
      - uses: actions/labeler@v5
        with:
          configuration-path: ".github/labeler.yml"
